import {observable, action} from 'mobx';
import React from 'react';

class TodoStore {
  constructor() {
    this.fetch();
  }

  //   @observable todo = [
  //     {title: 'hello', key: '1'},
  //     {title: 'hi', key: '2'},
  //   ];
  @observable fetchInterval = null;
  @observable covidData;

  // @observable srilankaTotalCases;
  // @observable srilankaLocalDeaths;
  // @observable srilankaTotalRecovered;

  @action init() {
    if (!this.fetchInterval) {
      this.fetch(); // initial fetch
      this.fetchInterval = setInterval(() => this.fetch(), 2000);
    }
  }

  @action fetch() {
    console.log('hit');
    fetch('https://hpb.health.gov.lk/api/get-current-statistical')
      .then(response => response.json())
      .then(responseJson => {
        // console.log(responseJson);
        this.covidData = responseJson;
        // console.log(this.covidData);
      })
      .catch(error => console.log(error)); //to catch the errors if any
  }

  @observable covidDataSample = [
    {
      success: true,
      message: 'Success',
      data: {
        update_date_time: '2020-03-25 17:46:40',
        local_new_cases: 0,
        local_total_cases: 102,
        local_total_number_of_individuals_in_hospitals: 255,
        local_deaths: 0,
        local_new_deaths: 0,
        local_recovered: 3,
        local_active_cases: 99,
        global_new_cases: 41371,
        global_total_cases: 435382,
        global_deaths: 19620,
        global_new_deaths: 1727,
        global_recovered: 111878,
        hospital_data: [
          {
            id: 1,
            hospital_id: 1,
            cumulative_local: 532,
            cumulative_foreign: 76,
            treatment_local: 98,
            treatment_foreign: 2,
            created_at: '2020-03-25 12:07:01',
            updated_at: null,
            deleted_at: null,
            cumulative_total: 608,
            treatment_total: 100,
            hospital: {
              id: 1,
              name: 'National Institute of Infectious Diseases',
              name_si: 'බෝවන රෝග පිළිබඳ ජාතික ආයතනය',
              name_ta: 'தேசிய தொற்று நோயியல் நிறுவனம்',
              created_at: '2020-03-25 01:37:33',
              updated_at: '2020-03-25 01:37:33',
              deleted_at: null,
            },
          },
          {
            id: 2,
            hospital_id: 2,
            cumulative_local: 74,
            cumulative_foreign: 5,
            treatment_local: 4,
            treatment_foreign: 0,
            created_at: '2020-03-25 12:07:01',
            updated_at: null,
            deleted_at: null,
            cumulative_total: 79,
            treatment_total: 4,
            hospital: {
              id: 2,
              name: 'National Hospital Sri Lanka',
              name_si: 'ශ්‍රී ලංකා ජාතික රෝහල',
              name_ta: 'இலங்கை தேசிய வைத்தியசாலை',
              created_at: '2020-03-25 01:37:33',
              updated_at: '2020-03-25 01:37:33',
              deleted_at: null,
            },
          },
          {
            id: 3,
            hospital_id: 3,
            cumulative_local: 92,
            cumulative_foreign: 2,
            treatment_local: 21,
            treatment_foreign: 0,
            created_at: '2020-03-25 12:07:01',
            updated_at: null,
            deleted_at: null,
            cumulative_total: 94,
            treatment_total: 21,
            hospital: {
              id: 3,
              name: 'TH - Ragama',
              name_si: 'ශික්ෂණ රෝහල - රාගම',
              name_ta: 'போதனா வைத்தியசாலை - ராகம',
              created_at: '2020-03-25 01:37:33',
              updated_at: '2020-03-25 01:37:33',
              deleted_at: null,
            },
          },
          {
            id: 4,
            hospital_id: 4,
            cumulative_local: 104,
            cumulative_foreign: 16,
            treatment_local: 4,
            treatment_foreign: 0,
            created_at: '2020-03-25 12:07:01',
            updated_at: null,
            deleted_at: null,
            cumulative_total: 120,
            treatment_total: 4,
            hospital: {
              id: 4,
              name: 'TH - Karapitiya',
              name_si: 'ශික්ෂණ රෝහල - කරපිටිය',
              name_ta: 'போதனா வைத்தியசாலை - கராபிடிய',
              created_at: '2020-03-25 01:37:33',
              updated_at: '2020-03-25 01:37:33',
              deleted_at: null,
            },
          },
          {
            id: 5,
            hospital_id: 5,
            cumulative_local: 48,
            cumulative_foreign: 2,
            treatment_local: 8,
            treatment_foreign: 0,
            created_at: '2020-03-25 12:07:01',
            updated_at: null,
            deleted_at: null,
            cumulative_total: 50,
            treatment_total: 8,
            hospital: {
              id: 5,
              name: 'TH - Anuradhapura',
              name_si: 'ශික්ෂණ රෝහල - අනුරාධපුර',
              name_ta: 'போதனா வைத்தியசாலை - அனுராதபுரம்',
              created_at: '2020-03-25 01:37:33',
              updated_at: '2020-03-25 01:37:33',
              deleted_at: null,
            },
          },
          {
            id: 6,
            hospital_id: 6,
            cumulative_local: 116,
            cumulative_foreign: 1,
            treatment_local: 14,
            treatment_foreign: 0,
            created_at: '2020-03-25 12:07:01',
            updated_at: null,
            deleted_at: null,
            cumulative_total: 117,
            treatment_total: 14,
            hospital: {
              id: 6,
              name: 'TH - Kurunegala',
              name_si: 'ශික්ෂණ රෝහල - කුරුණගල',
              name_ta: 'போதனா வைத்தியசாலை - குருநாகல்',
              created_at: '2020-03-25 01:37:33',
              updated_at: '2020-03-25 01:37:33',
              deleted_at: null,
            },
          },
          {
            id: 7,
            hospital_id: 7,
            cumulative_local: 24,
            cumulative_foreign: 1,
            treatment_local: 7,
            treatment_foreign: 0,
            created_at: '2020-03-25 12:07:01',
            updated_at: null,
            deleted_at: null,
            cumulative_total: 25,
            treatment_total: 7,
            hospital: {
              id: 7,
              name: 'TH- Jaffna',
              name_si: 'ශික්ෂණ රෝහල - යාපනය',
              name_ta: 'போதனா வைத்தியசாலை - யாழ்ப்பாணம்',
              created_at: '2020-03-25 01:37:33',
              updated_at: '2020-03-25 01:37:33',
              deleted_at: null,
            },
          },
          {
            id: 8,
            hospital_id: 8,
            cumulative_local: 55,
            cumulative_foreign: 6,
            treatment_local: 1,
            treatment_foreign: 0,
            created_at: '2020-03-25 12:07:01',
            updated_at: null,
            deleted_at: null,
            cumulative_total: 61,
            treatment_total: 1,
            hospital: {
              id: 8,
              name: 'National Hospital Kandy',
              name_si: 'ජාතික රෝහල - මහනුවර',
              name_ta: 'தேசிய வைத்தியசாலை கண்டி',
              created_at: '2020-03-25 01:37:33',
              updated_at: '2020-03-25 01:37:33',
              deleted_at: null,
            },
          },
          {
            id: 9,
            hospital_id: 9,
            cumulative_local: 18,
            cumulative_foreign: 0,
            treatment_local: 2,
            treatment_foreign: 0,
            created_at: '2020-03-25 12:07:01',
            updated_at: null,
            deleted_at: null,
            cumulative_total: 18,
            treatment_total: 2,
            hospital: {
              id: 9,
              name: 'TH – Batticaloa',
              name_si: 'ශික්ෂණ රෝහල - මඩකලපුව',
              name_ta: 'போதனா வைத்தியசாலை - மட்டக்களப்பு',
              created_at: '2020-03-25 01:37:33',
              updated_at: '2020-03-25 01:37:33',
              deleted_at: null,
            },
          },
          {
            id: 10,
            hospital_id: 10,
            cumulative_local: 93,
            cumulative_foreign: 4,
            treatment_local: 8,
            treatment_foreign: 0,
            created_at: '2020-03-25 12:07:01',
            updated_at: null,
            deleted_at: null,
            cumulative_total: 97,
            treatment_total: 8,
            hospital: {
              id: 10,
              name: 'DGH- Gampaha',
              name_si: 'දිස්ත්‍රික් මහ රෝහල - ගම්පහ',
              name_ta: 'மாவட்ட பொது வைத்தியசாலை - கம்பஹா',
              created_at: '2020-03-25 01:37:33',
              updated_at: '2020-03-25 01:37:33',
              deleted_at: null,
            },
          },
          {
            id: 11,
            hospital_id: 11,
            cumulative_local: 126,
            cumulative_foreign: 12,
            treatment_local: 10,
            treatment_foreign: 0,
            created_at: '2020-03-25 12:07:01',
            updated_at: null,
            deleted_at: null,
            cumulative_total: 138,
            treatment_total: 10,
            hospital: {
              id: 11,
              name: 'DGH – Negombo',
              name_si: 'දිස්ත්‍රික් මහ රෝහල - මීගමුව',
              name_ta: 'மாவட்ட பொது வைத்தியசாலை - நீர் கொழும்பு',
              created_at: '2020-03-25 01:37:33',
              updated_at: '2020-03-25 01:37:33',
              deleted_at: null,
            },
          },
          {
            id: 12,
            hospital_id: 12,
            cumulative_local: 74,
            cumulative_foreign: 0,
            treatment_local: 4,
            treatment_foreign: 0,
            created_at: '2020-03-25 12:07:01',
            updated_at: null,
            deleted_at: null,
            cumulative_total: 74,
            treatment_total: 4,
            hospital: {
              id: 12,
              name: 'TH – Rathnapura',
              name_si: 'ශික්ෂණ රෝහල - රත්නපුර',
              name_ta: 'போதனா வைத்தியசாலை - இரத்தினபுரி',
              created_at: '2020-03-25 01:37:33',
              updated_at: '2020-03-25 01:37:33',
              deleted_at: null,
            },
          },
          {
            id: 13,
            hospital_id: 13,
            cumulative_local: 21,
            cumulative_foreign: 0,
            treatment_local: 0,
            treatment_foreign: 0,
            created_at: '2020-03-25 12:07:01',
            updated_at: null,
            deleted_at: null,
            cumulative_total: 21,
            treatment_total: 0,
            hospital: {
              id: 13,
              name: 'PGH – Badulla',
              name_si: 'පළාත් මහ රෝහල - බදුල්ල',
              name_ta: 'மாகான அரச வைத்தியசாலை - பதுளை',
              created_at: '2020-03-25 01:37:33',
              updated_at: '2020-03-25 01:37:33',
              deleted_at: null,
            },
          },
          {
            id: 14,
            hospital_id: 14,
            cumulative_local: 25,
            cumulative_foreign: 0,
            treatment_local: 0,
            treatment_foreign: 0,
            created_at: '2020-03-25 12:07:01',
            updated_at: null,
            deleted_at: null,
            cumulative_total: 25,
            treatment_total: 0,
            hospital: {
              id: 14,
              name: 'LRH',
              name_si: 'රිජ්වේ ආර්යා ළමා රෝහල',
              name_ta: 'லேடி ரிட்ஜ்வே வைத்தியசாலை',
              created_at: '2020-03-25 01:37:33',
              updated_at: '2020-03-25 01:37:33',
              deleted_at: null,
            },
          },
          {
            id: 15,
            hospital_id: 15,
            cumulative_local: 3,
            cumulative_foreign: 0,
            treatment_local: 1,
            treatment_foreign: 0,
            created_at: '2020-03-25 12:07:01',
            updated_at: null,
            deleted_at: null,
            cumulative_total: 3,
            treatment_total: 1,
            hospital: {
              id: 15,
              name: 'DMH',
              name_si: 'ඩි සොයිසා කාන්තා රෝහල',
              name_ta: 'டி சோய்சா மகப்பேறு வைத்தியசாலை',
              created_at: '2020-03-25 01:37:33',
              updated_at: '2020-03-25 01:37:33',
              deleted_at: null,
            },
          },
          {
            id: 16,
            hospital_id: 16,
            cumulative_local: 57,
            cumulative_foreign: 6,
            treatment_local: 8,
            treatment_foreign: 0,
            created_at: '2020-03-25 12:07:01',
            updated_at: null,
            deleted_at: null,
            cumulative_total: 63,
            treatment_total: 8,
            hospital: {
              id: 16,
              name: 'DGH – Polonnaruwa',
              name_si: 'දිස්ත්‍රික් මහ රෝහල - පොලොන්නරුව',
              name_ta: 'மாவட்ட பொது வைத்தியசாலை - பொலன்னறுவை',
              created_at: '2020-03-25 01:37:33',
              updated_at: '2020-03-25 01:37:33',
              deleted_at: null,
            },
          },
          {
            id: 17,
            hospital_id: 17,
            cumulative_local: 16,
            cumulative_foreign: 0,
            treatment_local: 0,
            treatment_foreign: 0,
            created_at: '2020-03-25 12:07:01',
            updated_at: null,
            deleted_at: null,
            cumulative_total: 16,
            treatment_total: 0,
            hospital: {
              id: 17,
              name: 'TH - Kalubowila',
              name_si: 'දිස්ත්‍රික් මහ රෝහල - කලුබෝවිල',
              name_ta: 'கொழும்பு தெற்கு போதனா வைத்தியசாலை',
              created_at: '2020-03-25 01:37:33',
              updated_at: '2020-03-25 01:37:33',
              deleted_at: null,
            },
          },
          {
            id: 18,
            hospital_id: 18,
            cumulative_local: 7,
            cumulative_foreign: 0,
            treatment_local: 1,
            treatment_foreign: 0,
            created_at: '2020-03-25 12:07:01',
            updated_at: null,
            deleted_at: null,
            cumulative_total: 7,
            treatment_total: 1,
            hospital: {
              id: 18,
              name: 'Castle Street Teaching Hospital',
              name_si: 'කාසල් වීදියේ ශික්ෂණ රෝහල',
              name_ta: 'காசல் வீதி மகளிர் போதனா மருத்துவமனை',
              created_at: '2020-03-25 01:37:33',
              updated_at: '2020-03-25 01:37:33',
              deleted_at: null,
            },
          },
          {
            id: 19,
            hospital_id: 19,
            cumulative_local: 48,
            cumulative_foreign: 0,
            treatment_local: 11,
            treatment_foreign: 0,
            created_at: '2020-03-25 12:07:01',
            updated_at: null,
            deleted_at: null,
            cumulative_total: 48,
            treatment_total: 11,
            hospital: {
              id: 19,
              name: 'Base Hospital- Hambantota',
              name_si: 'මූලික රෝහල - හම්බන්තොට',
              name_ta: 'ஆதார வைத்தியசாலை- ஹம்பாந்தோட்டா',
              created_at: '2020-03-25 01:37:33',
              updated_at: '2020-03-25 01:37:33',
              deleted_at: null,
            },
          },
          {
            id: 20,
            hospital_id: 20,
            cumulative_local: 19,
            cumulative_foreign: 0,
            treatment_local: 6,
            treatment_foreign: 0,
            created_at: '2020-03-25 12:07:01',
            updated_at: null,
            deleted_at: null,
            cumulative_total: 19,
            treatment_total: 6,
            hospital: {
              id: 20,
              name: 'Base Hospital - Monaragala',
              name_si: 'මූලික රෝහල - මොනරාගල',
              name_ta: 'ஆதார வைத்தியசாலை- மோனராகலா',
              created_at: '2020-03-25 01:37:33',
              updated_at: '2020-03-25 01:37:33',
              deleted_at: null,
            },
          },
          {
            id: 21,
            hospital_id: 21,
            cumulative_local: 46,
            cumulative_foreign: 1,
            treatment_local: 26,
            treatment_foreign: 1,
            created_at: '2020-03-25 12:07:01',
            updated_at: null,
            deleted_at: null,
            cumulative_total: 47,
            treatment_total: 27,
            hospital: {
              id: 21,
              name: 'Base Hospital - Welikanda',
              name_si: 'මූලික රෝහල - වැලිකන්ද',
              name_ta: 'ஆதார வைத்தியசாலை- வாலிகண்ட',
              created_at: '2020-03-25 01:37:33',
              updated_at: '2020-03-25 01:37:33',
              deleted_at: null,
            },
          },
          {
            id: 22,
            hospital_id: 22,
            cumulative_local: 78,
            cumulative_foreign: 0,
            treatment_local: 11,
            treatment_foreign: 0,
            created_at: '2020-03-25 12:07:01',
            updated_at: null,
            deleted_at: null,
            cumulative_total: 78,
            treatment_total: 11,
            hospital: {
              id: 22,
              name: 'DGH-Kalutara',
              name_si: 'දිස්ත්‍රික් මහ රෝහල - කළුතර',
              name_ta: 'மாவட்ட பொது வைத்தியசாலை -களுத்துறை',
              created_at: '2020-03-25 01:37:33',
              updated_at: '2020-03-25 01:37:33',
              deleted_at: null,
            },
          },
          {
            id: 23,
            hospital_id: 23,
            cumulative_local: 6,
            cumulative_foreign: 0,
            treatment_local: 3,
            treatment_foreign: 0,
            created_at: '2020-03-25 12:07:01',
            updated_at: null,
            deleted_at: null,
            cumulative_total: 6,
            treatment_total: 3,
            hospital: {
              id: 23,
              name: 'Chest Hospital Welisara',
              name_si: 'ළය රෝහල - වැලිසර',
              name_ta: 'மார்பு வைத்தியசாலை -வெலிசரா',
              created_at: '2020-03-25 01:37:33',
              updated_at: '2020-03-25 01:37:33',
              deleted_at: null,
            },
          },
        ],
      },
    },
  ];

  @observable todoItem = 'hello , this works';
}

export default TodoStore;
